### ISSUE TITLE
thanks for the inspiration - and one small question

### ISSUE THREAD

**Issue by bitranox** [KenKundert/extended_pathlib#1]
Dear Ken,
thanks for the inspiration, I just put together something similar,
just to backport python3.8 pathlib to python 3.7, 3.6 (for older versions I dont care personally).
You might have a look and find it useful : https://travis-ci.org/github/bitranox/pathlib3x

When I looked over Your code, I found some Block Comments, probably for some sort of 
templating system, like 

```
 # is_readable {{{1
```
Sphinx is sometimes an overkill, would You please be so kind and point me to what You use there ? 

greetings from Vienna,

yours sincerely

Robert

**Comment by KenKundert** [comment]
Robert, the triple-brace syntax is used by Vim to implement folding.  I am finicky about folding, so I put in the fold marks myself. If you use Vim and would like folding, but don't want to bother putting in the fold marks by hand, try [Coiled Snake](https://github.com/kalekundert/vim-coiled-snake). It is a Vim rules file that automatically folds Python files.

-Ken

**Comment by bitranox** [comment]
I use pycharm, so folding is done there .... 
but thank You !
Robert
